### ISSUE TITLE
No build instructions

### ISSUE THREAD

**Issue by NieDzejkob** [Ross-Software/RNIX#5]
I cloned the repo and after running `make`,

    make: *** No rule to make target 'build-kernel', needed by 'build'.  Stop.

I'd recommend adding build instructions to the README.

**Comment by SpaceboyRoss01** [comment]
Run ‘make config CONFIG_ARCH=i386’

**Comment by SpaceboyRoss01** [comment]
Has this issue been fixed yet?

**Comment by NieDzejkob** [comment]
`make config CONFIG_ARCH=i386` lets you create an iso, but still nothing documents the process.

**Comment by SpaceboyRoss01** [comment]
You're wrong. `make config` will create the config files for the kernel and the makefile targets

**Comment by NieDzejkob** [comment]
What I meant is `make config` makes `make` work, but this is irrelevant.
